//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionOperations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionOperations()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public int PermissionOperationID { get; set; }
        public string PermissionID { get; set; }
        public string OperationID { get; set; }
    
        public virtual Operations Operations { get; set; }
        public virtual Permissions Permissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
