//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFG.DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Roles = new HashSet<Roles>();
        }
    
        public string Account { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public Nullable<System.DateTime> DateLastActivity { get; set; }
        public string Tel { get; set; }
        public string Ext { get; set; }
        public string CreatorAccount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string ModifierAccount { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Dept { get; set; }
        public Nullable<bool> IsCheckAccount { get; set; }
        public string NotesID { get; set; }
        public string Fac_ID { get; set; }
        public string Class_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Roles> Roles { get; set; }
    }
}
